# Generated by Django 6.0.4 on 2026-05-05 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid', '0003_account_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Used for soft deleting records.')),
                ('name', models.CharField(default='Emergency Fund', max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=30, max_digits=65)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('current_amount', models.DecimalField(decimal_places=30, default=0, max_digits=65)),
                ('accounts', models.ManyToManyField(blank=True, related_name='savings_goals', to='plaid.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
