# Generated by Django 6.0.4 on 2026-05-05 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid', '0004_savingsgoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingsgoal',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_split',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='plaid.transaction'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_subtype',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('investment', 'Investment'), ('credit', 'Credit'), ('depository', 'Depository'), ('loan', 'Loan'), ('brokerage', 'Brokerage'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='available_balance',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='iso_currency_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='mask',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='account',
            name='official_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='unofficial_currency_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='access_token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='institution_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='institution_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='new_accounts_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('GOOD', 'Good'), ('BAD', 'Bad')], max_length=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='transactions_cursor',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plaidlinkevent',
            name='error_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plaidlinkevent',
            name='error_type',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plaidlinkevent',
            name='event_type',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('EXIT', 'Exit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plaidlinkevent',
            name='link_session_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plaidlinkevent',
            name='request_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plaidlinkevent',
            name='user_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_owner',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='authorized_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='authorized_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='check_number',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='confidence_level',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='detailed_personal_finance_category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='iso_currency_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant_entity_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='personal_finance_category_icon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='primary_personal_finance_category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='unofficial_currency_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='website',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Used for soft deleting records.')),
                ('name', models.CharField(help_text='e.g. Groceries, Rent, Salary', max_length=100)),
                ('group', models.CharField(blank=True, help_text='e.g. Food, Housing, Income', max_length=50)),
                ('is_income', models.BooleanField(default=False)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('group', 'name'),
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='plaid.category'),
        ),
    ]
